#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "aarch64-linux-musl-gcc -DOPENSSL_THREADS  "
  #define PLATFORM "os/compiler"
  #define DATE "Tue Jun 10 11:05:36 CST 2025"
#endif
